/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE reportBaseService PLEASE EDIT ../report.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Report } from '../../domain/healthcare-blockchain_db/report';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Report.service.ts
 */

/*
 * SCHEMA DB Report
 *
	{
		date: {
			type: 'Date'
		},
		type: {
			type: 'String',
			enum : ["private", "public"]
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		doctor: {
			type: Schema.ObjectId,
			ref : "Report"
		},
	}
 *
 */
@Injectable()
export class ReportBaseService {

    contextUrl: string = environment.endpoint + '/report';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * ReportService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Report): Observable<Report> {
        return this.http
            .post<Report>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * ReportService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * ReportService.findBydoctor
    *   @description CRUD ACTION findBydoctor
    *   @param Objectid key Id della risorsa doctor da cercare
    *
    */
    findByDoctor(id: string): Observable<Report[]> {
        return this.http
            .get<Report[]>(this.contextUrl + '/findBydoctor/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * ReportService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Report> {
        return this.http
            .get<Report>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * ReportService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Report[]> {
        return this.http
            .get<Report[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * ReportService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Report): Observable<Report> {
        return this.http
            .post<Report>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
